database:
   type: mysql
   host: 185.35.187.91
   username: test
   password: test123
   database: dev_emf

debug:
  enabled: true #false will disable all below
  timespent: true
  category: db, action, template
  levels: error, warning, info
  ip: ["127.0.0.1"]

# image:
#     alias: {thumbnail:{width: 30}, large:{width: 800}}
#     generated_when_upload: "thumbnail, large"
