##
##Generate models for general use. eg. dm_location
##

pkgname = "entity"
output = "model/entity"
no-tests = "true"
#templates = [
#  "/Users/xc/go/caf-prototype/src/github.com/volatiletech/sqlboiler/templates",
#  "/Users/xc/go/caf-prototype/src/dm/sqlboiler/templates"
#]

[mysql]
host = "185.35.187.91"
user = "dev"
pass = "D!g!m@ker"
dbname = "dev_emf"
sslmode = "false"
whitelist = ['dm_location', 'dm_version']

[aliases.tables.dm_location]
up_plural = "Locations"
up_singular = "Location"
down_plural = "locations"
down_singular = "location"
