##
##Generate models for general use. eg. dm_location
##


#
# under this folder(sqlboiler), run <path of sqlboiler under bin> <path of mysql driver under bin>
# core contenttype/*.go to target

pkgname = "contenttype"
output = "contenttype"
no-tests = "true"
templates = [
  "../../../../../volatiletech/sqlboiler/templates",
  "core/templates"
]

[mysql]
user = "dev"
pass = "test123"
dbname = "dev_emf"
sslmode = "false"
whitelist = ['dm_relation','dm_version']

[imports.all]
third_party = ['"github.com/volatiletech/sqlboiler/boil"',
                '"github.com/volatiletech/sqlboiler/queries/qmhelper"',
                '"github.com/volatiletech/sqlboiler/strmangle"',
                '"github.com/pkg/errors"',
               '"github.com/volatiletech/sqlboiler/queries"',
               '. "dm/core/db"',
               '"dm/core/db"']

[aliases.tables.dm_relation]
up_plural = "Relations"
up_singular = "Relation"
down_plural = "relations"
down_singular = "relation"

[aliases.tables.dm_version]
up_plural = "Versions"
up_singular = "Version"
down_plural = "versions"
down_singular = "version"
