database:
   type: mysql
   host: 185.35.187.91
   username: test
   password: test123
   database: dev_emf ## test: dm_test


debug:
  enabled: "yes" #false will disable all below
  #types: ["callback_match"]
  timespent: "yes"
  category: db, action, template
  levels: error, warning, info
  ip: 127.0.0.1

##sites define all the sites
sites:
- routes:
  - host: "localhost:8089" ##separated by ",", support regular expression like{sub:[0-9]+}
    path: "demosite,test" ##separated by ","
  - host: "localhost:8089"
  root: 55
  default: 55
  template_folder:
    - "demosite"  #fist template folder will be used for base template(layout)
    - "test"

template:
    folder: ["demosite"]

# image:
#     alias: {thumbnail:{width: 30}, large:{width: 800}}
#     generated_when_upload: "thumbnail, large"
