content_view:
- contenttype: folder
  viewmode: full
  to: folder/full.html
- contenttype: article
  viewmode: full
  to: article/full.html
- viewmode: block
  to: block.html

user_view:
    - viewmode: full
      to: viewuser.html
